// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CameraControlBT-TDS3P

#include "../ui.h"

void ui_StartScreen_screen_init(void)
{
ui_StartScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_StartScreen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scrollbar_mode(ui_StartScreen, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_img_src( ui_StartScreen, &ui_img_286491071, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_StartTabView = lv_tabview_create(ui_StartScreen, LV_DIR_BOTTOM, 50);
lv_obj_set_width( ui_StartTabView, lv_pct(100));
lv_obj_set_height( ui_StartTabView, lv_pct(100));
lv_obj_clear_flag( ui_StartTabView, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

lv_obj_set_style_pad_left(lv_tabview_get_tab_btns(ui_StartTabView), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(lv_tabview_get_tab_btns(ui_StartTabView), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(lv_tabview_get_tab_btns(ui_StartTabView), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(lv_tabview_get_tab_btns(ui_StartTabView), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WirelessTabPage = lv_tabview_add_tab(ui_StartTabView, "Wireless");
lv_obj_set_flex_flow(ui_WirelessTabPage,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_WirelessTabPage, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_WirelessTabPage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_WirelessTabPage, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_img_src( ui_WirelessTabPage, &ui_img_286491071, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_pad_left(ui_WirelessTabPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_WirelessTabPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_WirelessTabPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_WirelessTabPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartBluetoothButton = lv_btn_create(ui_WirelessTabPage);
lv_obj_set_width( ui_StartBluetoothButton, 150);
lv_obj_set_height( ui_StartBluetoothButton, 150);
lv_obj_set_x( ui_StartBluetoothButton, 60 );
lv_obj_set_y( ui_StartBluetoothButton, 26 );
lv_obj_set_flex_flow(ui_StartBluetoothButton,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_StartBluetoothButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_StartBluetoothButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_StartBluetoothButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_StartBluetoothButton);
lv_img_set_src(ui_Image2, &ui_img_bluetooth3_64_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_StartBluetoothButton);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label7,"Bluetooth");

ui_SettingsTabPage = lv_tabview_add_tab(ui_StartTabView, "Settings");
lv_obj_set_flex_flow(ui_SettingsTabPage,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsTabPage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_img_src( ui_SettingsTabPage, &ui_img_286491071, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_SettingsContainer = lv_obj_create(ui_SettingsTabPage);
lv_obj_remove_style_all(ui_SettingsContainer);
lv_obj_set_width( ui_SettingsContainer, lv_pct(100));
lv_obj_set_height( ui_SettingsContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_flow(ui_SettingsContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_SettingsContainer);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Settings");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MotorZoomCheckbox = lv_checkbox_create(ui_SettingsTabPage);
lv_checkbox_set_text(ui_MotorZoomCheckbox,"Motor zoom");
lv_obj_set_width( ui_MotorZoomCheckbox, lv_pct(100));
lv_obj_set_height( ui_MotorZoomCheckbox, LV_SIZE_CONTENT);   /// 1
lv_obj_add_state( ui_MotorZoomCheckbox, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_MotorZoomCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_MotorZoomCheckbox, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MaintenanceContainer = lv_obj_create(ui_SettingsTabPage);
lv_obj_remove_style_all(ui_MaintenanceContainer);
lv_obj_set_height( ui_MaintenanceContainer, 220);
lv_obj_set_width( ui_MaintenanceContainer, lv_pct(100));
lv_obj_set_align( ui_MaintenanceContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_MaintenanceContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_MaintenanceContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_MaintenanceContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_MaintenanceContainer);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Maintenance");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RestartControllerButton = lv_btn_create(ui_MaintenanceContainer);
lv_obj_set_height( ui_RestartControllerButton, 50);
lv_obj_set_width( ui_RestartControllerButton, lv_pct(100));
lv_obj_set_align( ui_RestartControllerButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RestartControllerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RestartControllerButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_RestartControllerButton);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Restart Controller");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ResetAllSettingsButton = lv_btn_create(ui_MaintenanceContainer);
lv_obj_set_height( ui_ResetAllSettingsButton, 50);
lv_obj_set_width( ui_ResetAllSettingsButton, lv_pct(100));
lv_obj_set_align( ui_ResetAllSettingsButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ResetAllSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ResetAllSettingsButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_ResetAllSettingsButton);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"RESET all Settings");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AboutTabPage = lv_tabview_add_tab(ui_StartTabView, "About");
lv_obj_set_scroll_dir(ui_AboutTabPage, LV_DIR_VER);
lv_obj_set_style_bg_img_src( ui_AboutTabPage, &ui_img_286491071, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppNameLabel = lv_label_create(ui_AboutTabPage);
lv_obj_set_width( ui_AppNameLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AppNameLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_AppNameLabel,"CameraControl");
lv_obj_set_style_text_color(ui_AppNameLabel, lv_color_hex(0x69BCFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AppNameLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AppNameLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AppVersionLabel = lv_label_create(ui_AboutTabPage);
lv_obj_set_width( ui_AppVersionLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AppVersionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AppVersionLabel, 150 );
lv_obj_set_y( ui_AppVersionLabel, 0 );
lv_label_set_text(ui_AppVersionLabel,"0.0.1");
lv_obj_set_style_text_color(ui_AppVersionLabel, lv_color_hex(0x69BCFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AppVersionLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AppVersionLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AppCopyrightLabel = lv_label_create(ui_AboutTabPage);
lv_obj_set_width( ui_AppCopyrightLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AppCopyrightLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AppCopyrightLabel, 0 );
lv_obj_set_y( ui_AppCopyrightLabel, 28 );
lv_label_set_text(ui_AppCopyrightLabel,"Copyright 2024 \nDr. Thorsten Ludewig\nt.ludewig@gmail.com");
lv_obj_set_style_text_color(ui_AppCopyrightLabel, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AppCopyrightLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AppCopyrightLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AppLicenseLabel = lv_label_create(ui_AboutTabPage);
lv_obj_set_width( ui_AppLicenseLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AppLicenseLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AppLicenseLabel, 0 );
lv_obj_set_y( ui_AppLicenseLabel, 84 );
lv_label_set_text(ui_AppLicenseLabel,"License:");
lv_obj_set_style_text_color(ui_AppLicenseLabel, lv_color_hex(0x69BCFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AppLicenseLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AppLicenseLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Apache2LicenseLabel = lv_label_create(ui_AboutTabPage);
lv_obj_set_width( ui_Apache2LicenseLabel, 200);
lv_obj_set_height( ui_Apache2LicenseLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Apache2LicenseLabel, 0 );
lv_obj_set_y( ui_Apache2LicenseLabel, 104 );
lv_label_set_text(ui_Apache2LicenseLabel,"Licensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n      http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n");
lv_obj_set_style_text_color(ui_Apache2LicenseLabel, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Apache2LicenseLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoContainer = lv_obj_create(ui_StartTabView);
lv_obj_remove_style_all(ui_InfoContainer);
lv_obj_set_height( ui_InfoContainer, 24);
lv_obj_set_width( ui_InfoContainer, lv_pct(100));
lv_obj_set_align( ui_InfoContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_InfoContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_InfoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_InfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_InfoContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InfoContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PmuLabel = lv_label_create(ui_InfoContainer);
lv_obj_set_width( ui_PmuLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PmuLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PmuLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PmuLabel,"-");

lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StartBluetoothButton, ui_event_StartBluetoothButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MotorZoomCheckbox, ui_event_MotorZoomCheckbox, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RestartControllerButton, ui_event_RestartControllerButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ResetAllSettingsButton, ui_event_ResetAllSettingsButton, LV_EVENT_ALL, NULL);

}
